# Generated by Django 3.0.5 on 2020-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='titulo',
            field=models.CharField(max_length=1000),
        ),
    ]
