# Generated by Django 3.0.5 on 2020-05-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membrogrupo',
            old_name='user',
            new_name='Account',
        ),
    ]
