# Generated by Django 3.0.5 on 2020-05-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine', '0002_auto_20200503_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membrogrupo',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
