# Generated by Django 3.0.5 on 2020-05-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarantine', '0003_auto_20200503_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='karma',
            field=models.IntegerField(default=0, verbose_name='votos'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='karma',
            field=models.IntegerField(default=0, verbose_name='votos'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='votes',
            field=models.ManyToManyField(to='quarantine.Vote'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='votes',
            field=models.ManyToManyField(to='quarantine.Vote'),
        ),
    ]
