# Generated by Django 3.0.4 on 2020-05-05 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarantine', '0004_auto_20200504_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotoPublicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='votopublicacao',
            name='Publicacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarantine.Publicacao'),
        ),
        migrations.AddField(
            model_name='votopublicacao',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votocomentario',
            name='Comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarantine.Comentario'),
        ),
        migrations.AddField(
            model_name='votocomentario',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
